name: secrets and variables
on: workflow_dispatch
jobs:
  secrets:
    env:
    USERNAME: Admin
    PASSWORD: Admin123
    run-on: ubuntu-latest
step: 
    name: login database
    run: echo "login database using password $PASSWORD and username $USERNAME"
    
